## Linear Regression toy models 
This project will contain several regression models. Those a toy models based on artifitial created my me data.
The aim of this litlle projects is to show how to machine learning regression models works in the artifitial labolatory enviroment. So, those are only for pedagoical and trainig purposes. Besides that I will try to show some nontrivial fatures

### List of subprojects

The list will be expaded.
Each project consist of two jupyter noteboks: one generates data second performa larning model. The generated data are stored in the .\data folder
1. Linear regression
2. 